# EPICS Channel Access settings for Phoebus
# PLC IOC runs at 192.168.201.137:5064
# Local IOC runs on this machine
org.phoebus.pv.ca/addr_list=192.168.201.137 127.0.0.1
org.phoebus.pv.ca/auto_addr_list=false
